name 'bigcommercetechops-xhgui'
version '0.2.3'
description 'Installs and configures XHGui, a MongoDB-backed GUI for XHProf.'
dependency 'puppetlabs/vcsrepo', '>= 0.2.0'
dependency 'tPl0ch/composer', '>= 1.2.0'
dependency 'puppetlabs/mongodb', '>= 0.8.0'
dependency 'bigcommerce_techops/php5', '0.0.3', 'https://github.com/bigcommerce-techops/puppet-php5'
